### ISSUE TITLE
Using `Pixel Width` and `Pixel Height` is not enough

### ISSUE THREAD

**Issue by lacan** [qupath/qupath-extension-instanseg#99]
I have a dataset where the cells are rather large, taken with a spinning disk microscope

Pixel size is set to 0.5980 um as per the metadata of the microscope

Runing InstanSeg yields
![image](https://github.com/user-attachments/assets/1cd37c48-d4e1-42ff-917d-d45b7a5519c0)

Changing the pixel size to 0.2 um yields more expected results (Still wrong, but that's the data)

![image](https://github.com/user-attachments/assets/c8a1e592-d178-4d45-8f25-89c17f19191f)

Perhaps an assumption based solely on the pixel size is not sufficient...

**Comment by petebankhead** [comment]
I think it's more an issue of training data, which I discussed a bit [here](https://forum.image.sc/t/review-how-good-is-instanseg-at-segmenting-nuclei/101828/11).

I don't think there's anything in the training set that remotely resembles the spinning disk image.

We want to release multiple models and also simplify training custom models, but this will take a bit of time.

It's possible to adjust the [downsample in a script](https://github.com/qupath/qupath-extension-instanseg/blob/main/src/main/java/qupath/ext/instanseg/core/InstanSeg.java#L407) if you want to explore different effects without needing to change the image metadata.

Because I don't think this is an extension bug, I think it's more a topic for the main instanseg repo or (preferably) image.sc.

It's really important though. I would like to have a bigger discussion around assembling a good, fully-open training set. I plan to post something about that to image.sc, probably later in the week.
